#ifndef EEPROM_ADDRESS_DEFINITION_H_
#define EEPROM_ADDRESS_DEFINITION_H_

#define STRING_TERMINATION_CHARACTER 0x0D

// definitions based on eeprom_addresses_1v4_202302211330.xlsx

#define DEVICE_EEPROM_CHECK_ADDRESS 0
#define DEVICE_EEPROM_CHECK_DEFAULT_VALUE 0x00

#define DEVICE_SERIAL_NUMBER_ADDRESS 1
#define DEVICE_SERIAL_NUMBER_LENGTH 6
#define DEVICE_SERIAL_NUMBER_DEFAULT_VALUE 0x30

#define DEVICE_SERIAL_NUMBER_BACKUP_1_ADDRESS 16
#define DEVICE_SERIAL_NUMBER_BACKUP_2_ADDRESS 48

#define DEVICE_SENSOR_NAME_ADDRESS  32
#define COMMON_EEPROM_STRING_LENGTH 16
#define COMMON_EEPROM_STRING_START_VALUE 0x41	// 'A'
#define DEVICE_SENSOR_NAME_LENGTH COMMON_EEPROM_STRING_LENGTH
#define DEVICE_SENSOR_NAME_DEFAULT_START_VALUE COMMON_EEPROM_STRING_START_VALUE
#define DEVICE_SENSOR_NAME_DEFAULT_VALUE 0x03

#define DEVICE_SENSOR_SUB_NAME_ADDRESS 64
#define DEVICE_SENSOR_SUB_NAME_LENGTH COMMON_EEPROM_STRING_LENGTH
#define DEVICE_SENSOR_SUB_NAME_DEFAULT_VALUE 0x03

#define DEVICE_MODE_CONTROL_ADDRESS 96
#define DEVICE_MODE_CONTROL_DEFAULT_VALUE 0x01

#define DEVICE_COMMUNICATION_STYLE_ADDRESS 97
#define DEVICE_COMMUNICATION_STYLE_DEFAULT_VALUE 0x01

#define DEVICE_EXTERNAL_BAUD_RATE_ADDRESS 98
#define DEVICE_EXTERNAL_BAUD_RATE_DEFAULT_VALUE 0x07 //was 0x08 changed to start at default 5600

#define DEVICE_ARRAY_INTERVAL_ADDRESS 99
#define DEVICE_ARRAY_INTERVAL_DEFAULT_VALUE 0x00

#define DEVICE_AUTONOMOUS_ON_DELAY_HOUR_ADDRESS 100
#define DEVICE_AUTONOMOUS_ON_DELAY_HOUR_DEFAULT_VALUE 0
#define DEVICE_AUTONOMOUS_ON_DELAY_MINUTES_ADDRESS 101
#define DEVICE_AUTONOMOUS_ON_DELAY_MINUTES_DEFAULT_VALUE 0
#define DEVICE_AUTONOMOUS_ON_DELAY_MAXIMUM_HOUR_VALUE 24
#define DEVICE_AUTONOMOUS_ON_DELAY_MAXIMUM_MINUTE_VALUE 0
#define DEVICE_AUTONOMOUS_ON_DELAY_MINIMUM_HOUR_VALUE 0
#define DEVICE_AUTONOMOUS_ON_DELAY_MINIMUM_MINUTE_VALUE 0
#define DEVICE_AUTONOMOUS_ON_DELAY_MINIMUM_MINUTES_VALUE_ABOVE_ZERO 1 //from 5. SG 110723

#define DEVICE_SAVE_SQUARE_WAVE_DATA_ADDRESS 102
#define DEVICE_SAVE_SQUARE_WAVE_DATA_DEFAULT_VALUE 0x02

#define DEVICE_IMMERSION_RULE_ADDRESS 103
#define DEVICE_IMMERSION_RULE_DEFAULT_VALUE 0x01

#define DEVICE_ARRAY_HEALTH_ADDRESS 104
#define DEVICE_ARRAY_HEALTH_DEFAULT_VALUE 0x00

#define DEVICE_INTERFACE_ADDRESS 105
#define DEVICE_INTERFACE_DEFAULT_VALUE 0x01

#define DEVICE_MODBUS_ADDR_ADDRESS 106
#define DEVICE_MODBUS_ADDR_DEFAULT_VALUE 0x55

#define DEVICE_IMMERSION_RULE_INTERVAL_ADDRESS 107
#define DEVICE_IMMERSION_RULE_INTERVAL_DEFAULT_VALUE 0x00

#define DEVICE_SCAN_HEALTH_ADDRESS 108 //4 bytes needed

#define DEVICE_DRIVER_FIRMWARE_VERSION_ADDRESS 128
#define DEVICE_DRIVER_FIRMWARE_VERSION_LENGTH COMMON_EEPROM_STRING_LENGTH
#define DEVICE_DRIVER_FIRMWARE_VERSION_START_VALUE STRING_TERMINATION_CHARACTER

#define DEVICE_MANUFACTURER_NAME_ADDRESS 160
#define DEVICE_MANUFACTURER_NAME_LENGTH COMMON_EEPROM_STRING_LENGTH
#define DEVICE_MANUFACTURER_NAME_DEFAULT_START_VALUE COMMON_EEPROM_STRING_START_VALUE

#define DEVICE_PH_OUTPUT_STYLE_ADDRESS 192
#define DEVICE_PH_OUTPUT_STYLE_DEFAULT_VALUE 0x02

#define DEVICE_TEMPERATURE_SLOPE_ADDRESS 193
#define DEVICE_TEMPERATURE_SLOPE_LENGTH 4

#define DEVICE_TEMPERATURE_CALIBRATION_ADDRESS 197
#define DEVICE_TEMPERATURE_CALIBRATION_LENGTH 12

#define DEVICE_TEMPERATURE_CALIBRATION_BACKUP_1_ADDRESS 209

#define DEVICE_SENSOR_HEARTBEAT_STYLE_ADDRESS 224
#define DEVICE_SENSOR_HEARTBEAT_STYLE_DEFAULT_VALUE 0x02

#define DEVICE_PH_ARRAY_INDEX 226
#define DEVICE_PH_ARRAY_INDEX_DEFAULT_VALUE 0x00

#define DEVICE_PH_ARRAY_INDEX_LOOPED_FLAG 227
#define DEVICE_PH_ARRAY_INDEX_LOOPED_FLAG_DEFAULT_VALUE 0x00

#define DEVICE_PH_RUNNING_AVERAGE_START 228 //4 bytes needed
#define DEVICE_LAST_TEMPERATURE_START 232 //4 bytes needed
#define DEVICE_AVG_IREF_PEAK_POTENTIAL_START 236 //4 bytes needed
#define DEVICE_AVG_PH_PEAK_POTENTIAL_START 240 //4 bytes needed
#define DEVICE_AVG_PH_PEAK_POTENTIAL_STORED 244
#define DEVICE_PRECONDITIONING_DONE 245
#define DEVICE_highest_PH_QAQC_START 246 //4 bytes needed
#define DEVICE_ABRADED 250
#define DEVICE_COND_REF_HOLD_TIME_CODE 251

#define DEVICE_TEMPERATURE_CALIBRATION_BACKUP_2_ADDRESS 276

#define DEVICE_ELECTRODE_ARRAY_LOOPED 292

#define DEVICE_SCAN_ANB_OR_ALTERNATE_HEAD_ADDRESS 293
#define DEVICE_SCAN_ANB_OR_ALT_HEAD_DEFAULT_VALUE COMMAND_OPTION_ANBSENSORS_HEAD

#define DEVICE_SENSOR_SYSTEM_MODBUS_ADDRESS 294
#define DEVICE_SENSOR_SYSTEM_MODBUS_ADDRESS_DEFAULT_VALUE 0x55

#define DEVICE_IREF_HEALTH_ADDRESS 295
#define DEVICE_IREF_SECONDARY_HEALTH_ADDRESS 296
#define DEVICE_IREF_LAST_USED_ADDRESS 297
#define DEVICE_IREF_HEALTH_BAD_COUNT_ADDRESS 298

#define DEVICE_HEALTH_ARRAY_START 299
#define DEVICE_HEALTH_ARRAY_LENGTH NUMBER_OF_PH_ELECTRODES_MAX

#define DEVICE_GAIN_ARRAY_START 320
#define DEVICE_GAIN_ARRAY_LENGTH GAIN_ARRAY_SIZE
#define DEVICE_ELECTRODE_GAIN_BUMPED_START 352 //no longer used
#define DEVICE_GAIN_BUMP_FAILED_START 384 //no longer used

#define DEVICE_INTERFACE_VERSION_ADDRESS 416 //2 bytes

#define DEVICE_USE_SDCARD_ADDRESS 418
#define DEVICE_LOOPS_SINCE_LAST_GOOD_PH_ADDRESS 419
#define DEVICE_LOOPS_SINCE_LAST_CORRECTION_ADDRESS 420
#define DEVICE_LOOP_COUNT_ADDRESS 421 //3 bytes used

#define DEVICE_POWER_ADDRESS 424
#define DEVICE_SALINITY_RANGE_ADDRESS 425
#define DEVICE_FRESH_ELECTRODES_ADDRESS 426
#define DEVICE_LOOPS_SINCE_LAST_EVENT_ADDRESS 427
#define DEVICE_NEXT_SET_ELECTRODE_ADDRESS 428
#define DEVICE_LOOPS_SINCE_START_ADDRESS 429
#define DEVICE_PHS_PER_LOOP_ADDRESS 430

#define DEVICE_PULSE_AMPLITUDES_START 448
#define DEVICE_FREQUENCIES_START 464
#define DEVICE_PEAK_POTENTIAL_OFFSETS_START 480
#define DEVICE_CLIPPED_AT_GAIN_START 532

#define DEVICE_SIMULTANEOUS_SCAN_EXTRA_ELECTRODE_NUMBER_ADDRESS 565

#define DEVICE_SCAN_N_NO_OF_PH_ELECTRODES_ADDRESS 566

#define DEVICE_LAST_ELECTRODE_NUMBER_ADDRESS 567
#define DEVICE_LAST_ELECTRODE_NUMBER_DEFAULT_VALUE 1

#define DEVICE_IREF_SECONDARY_HEALTH_BAD_COUNT_ADDRESS 568
#define DEVICE_FAST_PROFILING_ADDRESS 569
#define DEVICE_SCAN_C_PH_SCAN_START_NUMBER_ADDRESS 570 //not used, redeploy if needed

#define DEVICE_PH_ARRAY_START 571
#define DEVICE_PH_ARRAY_LENGTH PH_ARRAY_SIZE_MAX
#define DEVICE_PH_ARRAY_DEFAULT_VALUES 0

#define DEVICE_PEAK_POTENTIALS_START 675 //571 + (13*2)*4
#define DEVICE_QAQCS_START 727 //675 + 13*4 - next available address is 727 + 13*4 = 779

#define DEVICE_PH_PEAKS_LOOPS_START 779 //727 + (13*2)*4
#define DEVICE_IREF_PEAKS_LOOPS_START 831 //779 + 13*4 - next available address 831 + 13*4 = 883

#endif /* EEPROM_ADDRESS_DEFINITION_H_ */
